# Étape de build
FROM rust:1.70 as builder

# Créer un projet vide pour mettre en cache les dépendances
WORKDIR /usr/src/chatbot
RUN USER=root cargo new --bin chatbot
WORKDIR /usr/src/chatbot/chatbot
COPY Cargo.toml Cargo.lock ./
RUN cargo build --release
RUN rm src/*.rs

# Copier le code source réel
COPY src ./src

# Construire pour de vrai
RUN rm ./target/release/deps/chatbot*
RUN cargo build --release

# Étape finale
FROM debian:bullseye-slim

# Installer les dépendances nécessaires
RUN apt-get update && apt-get install -y libssl-dev ca-certificates && rm -rf /var/lib/apt/lists/*

# Copier l'exécutable depuis l'étape de build
COPY --from=builder /usr/src/chatbot/chatbot/target/release/chatbot /usr/local/bin/chatbot

# Créer un utilisateur non-root
RUN useradd -ms /bin/bash chatbot
USER chatbot

# Définir le répertoire de travail
WORKDIR /home/chatbot

# Copier le fichier .env s'il existe
COPY --chown=chatbot:chatbot .env .env

# Exposer le port sur lequel l'application s'exécute
EXPOSE 3000

# Commande pour exécuter l'application
CMD ["chatbot"]
